# ---------- GRIDLAYOUT.KV ----------
 
# Define the number of columns and rows
# Define the spacing between children in pixels
 
<GridLayout>:
    cols: 2
    rows: 2
    spacing: 10
 
    # Set the size by passing None to size_hint_x
    # and then pass the width
 
    Button:
        text: "1st"
        size_hint_x: None
        width: 200
    Button:
        text: "2nd"
    Button:
        text: "3rd"
        size_hint_x: None
        width: 200
    Button:
        text: "4th"
